/*
 * Silicon Laboratories Confidential
 * Copyright 2011 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#include "..\..\bsp.h"


#define Si4455ChipReadyPend                     Si4455ChipPend2
#define Si4455CmdErrPend                        Si4455ChipPend3
#define Si4455StateChangePend                   Si4455ChipPend4
#define Si4455FifoUnderflowOverflowErrorPend    Si4455ChipPend5
#define Si4455CalPend                           Si4455ChipPend6

#define Si4455SyncDetectPend                    Si4455ModemPend0
#define Si4455PreambleDetectPend                Si4455ModemPend1
#define Si4455InvalidPreamblePend               Si4455ModemPend2
#define Si4455RssiPend                          Si4455ModemPend3
#define Si4455RssiJumpPend                      Si4455ModemPend4
#define Si4455InvalidSyncPend                   Si4455ModemPend5
#define Si4455PostambleDetectPend               Si4455ModemPend6

#define Si4455RxFifoAlmostFullPend              Si4455PhPend0
#define Si4455TxFifoAlmostEmptyPend             Si4455PhPend1
#define Si4455Crc32ErrorPend                    Si4455PhPend3
#define Si4455PacketRxPend                      Si4455PhPend4
#define Si4455PacketSentPend                    Si4455PhPend5

/*!
 * Do NOT use SEG_BDATA as that is not understood by SDCC!
 * Use BITS, WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY instead to allocate and
 * handle bit arrays in a convenient way.
 *
 * Allocate all 8bits if WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY macros
 * are to be used. Otherwise these macros would read/write bits that are
 * placed within that byte by the linker.
 */
BITS(Si4455PhPend0, 0);
BITS(Si4455PhPend1, 1);
BITS(Si4455PhPend3, 3);
BITS(Si4455PhPend4, 4);
BITS(Si4455PhPend5, 5);

BITS(Si4455ModemPend0, 0);
BITS(Si4455ModemPend1, 1);
BITS(Si4455ModemPend2, 2);
BITS(Si4455ModemPend3, 3);
BITS(Si4455ModemPend4, 4);
BITS(Si4455ModemPend5, 5);
BITS(Si4455ModemPend6, 6);

BITS(Si4455ChipPend2, 2);
BITS(Si4455ChipPend3, 3);
BITS(Si4455ChipPend4, 4);
BITS(Si4455ChipPend5, 5);
BITS(Si4455ChipPend6, 6);

/*!
 * This function is used to handle the assertion of nIRQ of the si4455 chip.
 *
 * @note This function can take up to 6 ms depending on the startup time of the
 * si4455 chip.
 *
 */
void si4455_nirq_process(void)
{
#ifdef SI4455_USER_CONFIG_USE_FRR_ABC_FOR_NIRQ
    SEGMENT_VARIABLE(pendBits[3], U8, SEG_DATA);

    si4455_frr_read();
#else
    si4455_get_int_status(0, 0, 0);
    WRITE_TO_BIT_ARRAY(Si4455PhPend, Si4455Cmd.GET_INT_STATUS.PH_PEND);
    WRITE_TO_BIT_ARRAY(Si4455ModemPend, Si4455Cmd.GET_INT_STATUS.MODEM_PEND);
    WRITE_TO_BIT_ARRAY(Si4455ChipPend, Si4455Cmd.GET_INT_STATUS.CHIP_PEND);
#endif
}
